services:
  - type: web
    name: sif-sentinel-backend
    env: python
    rootDir: backend
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    
    # We are adding the persistent disk back so your SQLite data never deletes!
    disk:
      name: sif-database
      mountPath: /data
      sizeGB: 1

    envVars:
      - key: DATABASE_URL
        value: sqlite:////data/sif_sentinel.db
      - key: ALLOWED_ORIGINS
        value: '["*"]'
